// @generated by a fixture codegen. DO NOT EDIT.

// A function-local `use` inside a generated file must NOT be linted: codegen
// owns the layout and the file is never hand-edited.
pub fn run() -> String {
    use std::fmt::Write;
    let mut out = String::new();
    let _ = write!(out, "gen");
    out
}
