//! Request ID value object.
//!
//! Generated by the caller for each outgoing request; echoed back by the agent
//! in response subject names and the `X-Req-Id` header so the caller can correlate
//! responses to the correct JetStream consumer.

#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct ReqId(String);

impl ReqId {
    pub fn new() -> Self {
        Self(uuid::Uuid::now_v7().simple().to_string())
    }

    pub fn from_header(s: impl Into<String>) -> Self {
        Self(s.into())
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl Default for ReqId {
    fn default() -> Self {
        Self::new()
    }
}

impl std::fmt::Display for ReqId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.0)
    }
}

impl std::ops::Deref for ReqId {
    type Target = str;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

#[cfg(test)]
impl ReqId {
    pub fn from_test(s: &str) -> Self {
        Self(s.to_string())
    }
}

#[cfg(test)]
mod tests;
