apiVersion: v1
kind: Service
metadata:
  name: {{ include "agentgateway.fullname" . }}
  labels: {{- include "agentgateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http-probe
      port: {{ .Values.service.port }}
      targetPort: http-probe
      protocol: TCP
  selector: {{- include "agentgateway.selectorLabels" . | nindent 4 }}
