// edition:2024

use std::fmt;

// A type implementing `Error` without the suffix: the violation. `thiserror` is
// unavailable in the dependency-free `ui` directory, so the derive it would
// generate is stood in for by a hand-written impl (silenced for
// `manual_error_impl`, whose concern is orthogonal).
#[derive(Debug)]
struct EmptySecret;

impl fmt::Display for EmptySecret {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("secret must not be empty")
    }
}

#[allow(manual_error_impl)]
impl std::error::Error for EmptySecret {}

// An enum error without the suffix is a violation just the same.
#[derive(Debug)]
enum Decode {
    Truncated,
}

impl fmt::Display for Decode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("truncated")
    }
}

#[allow(manual_error_impl)]
impl std::error::Error for Decode {}

// The `Error` impl generated by a derive/macro comes from an expansion, yet the
// name it governs is the user's `MacroSecret`: still a violation.
macro_rules! derive_error {
    ($ty:ty) => {
        impl std::error::Error for $ty {}
    };
}

#[derive(Debug)]
struct MacroSecret;

impl fmt::Display for MacroSecret {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("macro secret")
    }
}

derive_error!(MacroSecret);

// Correctly suffixed error type: allowed.
#[derive(Debug)]
struct EmptySecretError;

impl fmt::Display for EmptySecretError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("secret must not be empty")
    }
}

#[allow(manual_error_impl)]
impl std::error::Error for EmptySecretError {}

// The root error enum named exactly `Error` ends in "Error": allowed.
#[derive(Debug)]
enum Error {
    Io,
}

impl fmt::Display for Error {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("io")
    }
}

#[allow(manual_error_impl)]
impl std::error::Error for Error {}

// A type that does not implement `Error` is never linted, suffix or not.
struct NotAnError;

impl fmt::Display for NotAnError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("not an error")
    }
}

fn main() {}
