// edition:2024
// DO NOT EDIT. Generated by Weaver from `otel/semconv/`.
// A module-level constant in a generated file (Weaver stamps `DO NOT EDIT`, not
// `@generated`) cannot be hand-moved into a `constants` module, so the lint must
// NOT fire.
#![allow(dead_code)]

pub const URL_PATH: &str = "url.path";

fn main() {}
