//! Request ID value object.
//!
//! Generated by the bridge for each outgoing request and used as the JSON-RPC
//! `id`; echoed back by the runner in the `Jsonrpc-Id` header so the bridge can
//! tell apart the responses of the requests it has in flight on one session.

/// Opaque request correlation ID.
///
/// Created by the bridge via [`ReqId::new`] (UUID v7), then handed to the codec
/// as the JSON-RPC `id`. The runner recovers it from the `Jsonrpc-Id` header via
/// [`ReqId::from_header`] and echoes it on the reply. It never appears in a
/// subject (ADR#0055): responses land on a session-scoped subject and the
/// bridge demuxes on the header. It is deliberately not carried a second time in
/// a transport-specific header: a JSON-RPC message without an `id` is a
/// notification, so absence is the request/notification discriminator.
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct ReqId(String);

impl ReqId {
    /// Generates a new time-ordered request ID (UUID v7).
    pub fn new() -> Self {
        Self(uuid::Uuid::now_v7().to_string())
    }

    /// Wraps a raw string read from a NATS header.
    pub fn from_header(s: impl Into<String>) -> Self {
        Self(s.into())
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl Default for ReqId {
    fn default() -> Self {
        Self::new()
    }
}

impl std::fmt::Display for ReqId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.0)
    }
}

impl std::ops::Deref for ReqId {
    type Target = str;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

#[cfg(test)]
impl ReqId {
    pub fn from_test(s: &str) -> Self {
        Self(s.to_string())
    }
}

#[cfg(test)]
mod tests;
