//! # trogon-source-gitlab
//!
//! GitLab webhook receiver that publishes events to NATS JetStream.
//!
//! ## How it works
//!
//! 1. GitLab sends `POST /webhook` with `webhook-id`, `webhook-timestamp`,
//!    `webhook-signature`, `X-GitLab-Event`, `X-Gitlab-Webhook-UUID`, `Idempotency-Key`, and `X-Gitlab-Instance`
//!    headers plus a JSON payload.
//! 2. The server validates the `webhook-signature` HMAC against the integration `signing_token`.
//! 3. Events are published to NATS JetStream on `{subject_prefix}.{event}` subjects
//!    (e.g. `gitlab.push`, `gitlab.merge_request_hook`).
//! 4. The JetStream stream is created
//!    automatically on startup if it doesn't exist.
//! 5. Unroutable payloads (missing/invalid event header) are published to
//!    `{prefix}.unroutable` with an `X-GitLab-Reject-Reason` header.
//!
//! ## NATS message format
//!
//! - **Subject**: `{subject_prefix}.{X-GitLab-Event}` (e.g. `gitlab.push`)
//! - **Headers**: `X-GitLab-Event`, `X-GitLab-Webhook-UUID`, `X-GitLab-Instance`
//! - **Dedup**: `Nats-Msg-Id` set from `Idempotency-Key` (stable across retries)
//! - **Payload**: raw JSON body from GitLab
//!
//! ## Configuration
//!
//! Configure GitLab webhooks in TOML under `[sources.gitlab.integrations.<integration>.webhook]`.
//! The `signing_token` field is required and must be a `whsec_` signing token generated by GitLab.
//!
//! | Setting | Default | Description |
//! |---|---|---|
//! | `signing_token` | **required** | `whsec_` signing token generated by GitLab |
//! | `timestamp_tolerance_secs` | `300` | Maximum accepted signature timestamp age |
//! | `subject_prefix` | `gitlab-{integration}` | NATS subject prefix |
//! | `stream_name` | `GITLAB_{integration}` | JetStream stream name |
//! | `stream_max_age_secs` | `604800` | Max age of messages in JetStream |
//! | `nats_ack_timeout_secs` | `10` | NATS publish ack timeout |

pub mod config;
pub mod constants;
pub mod gitlab_signing_token;
pub mod server;
pub mod signature;
pub use config::GitlabConfig;
pub use gitlab_signing_token::GitLabSigningToken;
pub use server::{provision, router};
