//! NATS-safe task identifier value object.
//!
//! Task IDs scope the per-task event stream subject `{prefix}.task.{task_id}.events.{req_id}`.
//! Generated by the agent on `message/send` or `message/stream`. The A2A spec recommends
//! UUIDs; we accept any single NATS token to remain transport-agnostic.

use trogon_nats::NatsToken;
use trogon_nats::SubjectTokenViolation;

#[derive(Debug, Clone, PartialEq)]
pub struct TaskIdError(pub SubjectTokenViolation);

impl std::fmt::Display for TaskIdError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match &self.0 {
            SubjectTokenViolation::Empty => write!(f, "task_id must not be empty"),
            SubjectTokenViolation::InvalidCharacter(ch) => {
                write!(f, "task_id contains invalid character: {:?}", ch)
            }
            SubjectTokenViolation::TooLong(len) => {
                write!(f, "task_id is too long: {} characters (max 128)", len)
            }
        }
    }
}

impl std::error::Error for TaskIdError {}

#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct A2aTaskId(NatsToken);

impl A2aTaskId {
    pub fn new(s: impl AsRef<str>) -> Result<Self, TaskIdError> {
        NatsToken::new(s).map(Self).map_err(TaskIdError)
    }

    /// Generates a new time-ordered task id (UUID v7, hyphens stripped to satisfy
    /// NATS token rules and keep subjects compact).
    pub fn generate() -> Self {
        let id = uuid::Uuid::now_v7().simple().to_string();
        // simple() format strips hyphens; only hex chars remain — always a valid NatsToken.
        Self(NatsToken::new(id).expect("uuid v7 simple format is a valid NATS token"))
    }

    pub fn as_str(&self) -> &str {
        self.0.as_str()
    }
}

impl std::fmt::Display for A2aTaskId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

impl std::ops::Deref for A2aTaskId {
    type Target = str;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a2a_task_id_valid() {
        assert!(A2aTaskId::new("task-1").is_ok());
        assert_eq!(A2aTaskId::new("t").unwrap().as_str(), "t");
    }

    #[test]
    fn a2a_task_id_rejects_invalid() {
        assert!(A2aTaskId::new("").is_err());
        assert!(A2aTaskId::new("a.b").is_err());
        assert!(A2aTaskId::new("a*").is_err());
        assert!(A2aTaskId::new("a>").is_err());
    }

    #[test]
    fn a2a_task_id_generate_unique() {
        let a = A2aTaskId::generate();
        let b = A2aTaskId::generate();
        assert_ne!(a.as_str(), b.as_str());
        assert_eq!(a.as_str().len(), 32, "UUID v7 simple form is 32 hex chars");
    }

    #[test]
    fn a2a_task_id_display() {
        let id = A2aTaskId::new("abc").unwrap();
        assert_eq!(format!("{id}"), "abc");
    }

    #[test]
    fn task_id_error_display() {
        assert_eq!(
            format!("{}", TaskIdError(SubjectTokenViolation::Empty)),
            "task_id must not be empty"
        );
        assert_eq!(
            format!("{}", TaskIdError(SubjectTokenViolation::InvalidCharacter('.'))),
            "task_id contains invalid character: '.'"
        );
        assert_eq!(
            format!("{}", TaskIdError(SubjectTokenViolation::TooLong(129))),
            "task_id is too long: 129 characters (max 128)"
        );
    }
}
