//! NATS-safe task identifier value object.
//!
//! Task IDs scope the per-task event stream subject `{prefix}.tasks.{task_id}.events.{req_id}`.
//! Generated by the agent on `message/send` or `message/stream`. The A2A spec recommends
//! UUIDs; we accept any single NATS token to remain transport-agnostic.

use trogon_nats::NatsToken;
use trogon_nats::SubjectTokenViolation;

#[derive(Debug, Clone, PartialEq, thiserror::Error)]
pub enum TaskIdError {
    #[error("task_id must not be empty")]
    Empty,
    #[error("task_id contains invalid character: {0:?}")]
    InvalidCharacter(char),
    #[error("task_id is too long: {0} characters (max 128)")]
    TooLong(usize),
}

impl From<SubjectTokenViolation> for TaskIdError {
    fn from(violation: SubjectTokenViolation) -> Self {
        match violation {
            SubjectTokenViolation::Empty => Self::Empty,
            SubjectTokenViolation::InvalidCharacter(ch) => Self::InvalidCharacter(ch),
            SubjectTokenViolation::TooLong(len) => Self::TooLong(len),
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct A2aTaskId(NatsToken);

impl A2aTaskId {
    pub fn new(s: impl AsRef<str>) -> Result<Self, TaskIdError> {
        NatsToken::new(s).map(Self).map_err(TaskIdError::from)
    }

    /// Generates a new time-ordered task id (UUID v7, hyphens stripped to satisfy
    /// NATS token rules and keep subjects compact).
    #[allow(clippy::expect_used)]
    pub fn generate() -> Self {
        let id = uuid::Uuid::now_v7().simple().to_string();
        // simple() format strips hyphens; only hex chars remain — always a valid NatsToken.
        Self(NatsToken::new(id).expect("uuid v7 simple format is a valid NATS token"))
    }

    pub fn as_str(&self) -> &str {
        self.0.as_str()
    }
}

impl std::fmt::Display for A2aTaskId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

impl std::ops::Deref for A2aTaskId {
    type Target = str;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

#[cfg(test)]
mod tests;
