// edition:2024
// @generated by a codegen step; its module layout is not hand-authored.
// A module-level constant in a generated file cannot be hand-moved into a
// `constants` module, so the lint must NOT fire.
#![allow(dead_code)]

const GENERATED_LIMIT: usize = 512;

fn main() {}
