//! Request ID value object.
//!
//! Generated by the bridge for each outgoing request; echoed back by the runner
//! in response subject names and `X-Req-Id` headers so the bridge can correlate
//! responses to the correct JetStream consumer.

/// Opaque request correlation ID.
///
/// Created by the bridge via [`ReqId::new`] (UUID v4). The runner reads it from
/// the `X-Req-Id` header and reconstructs it with [`ReqId::from_header`] to
/// embed in response subject names.
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct ReqId(String);

impl ReqId {
    /// Generates a new random request ID (UUID v4).
    pub fn new() -> Self {
        Self(uuid::Uuid::now_v7().to_string())
    }

    /// Wraps a raw string read from a NATS header.
    pub fn from_header(s: impl Into<String>) -> Self {
        Self(s.into())
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl Default for ReqId {
    fn default() -> Self {
        Self::new()
    }
}

impl std::fmt::Display for ReqId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.0)
    }
}

impl std::ops::Deref for ReqId {
    type Target = str;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

#[cfg(test)]
impl ReqId {
    pub fn from_test(s: &str) -> Self {
        Self(s.to_string())
    }
}
