//! Request ID value object.
//!
//! Generated by the bridge for each outgoing request; echoed back by the runner
//! in response subject names and `X-Req-Id` headers so the bridge can correlate
//! responses to the correct JetStream consumer.

/// Opaque request correlation ID.
///
/// Created by the bridge via [`ReqId::new`] (UUID v7). The runner reads it from
/// the `X-Req-Id` header and reconstructs it with [`ReqId::from_header`] to
/// embed in response subject names.
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct ReqId(String);

impl ReqId {
    /// Generates a new time-ordered request ID (UUID v7).
    pub fn new() -> Self {
        Self(uuid::Uuid::now_v7().to_string())
    }

    /// Wraps a raw string read from a NATS header.
    pub fn from_header(s: impl Into<String>) -> Self {
        Self(s.into())
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl Default for ReqId {
    fn default() -> Self {
        Self::new()
    }
}

impl std::fmt::Display for ReqId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.0)
    }
}

impl std::ops::Deref for ReqId {
    type Target = str;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

#[cfg(test)]
impl ReqId {
    pub fn from_test(s: &str) -> Self {
        Self(s.to_string())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn new_generates_non_empty_id() {
        let id = ReqId::new();
        assert!(!id.as_str().is_empty());
    }

    #[test]
    fn default_generates_non_empty_id() {
        let id = ReqId::default();
        assert!(!id.as_str().is_empty());
    }

    #[test]
    fn from_header_roundtrips() {
        let id = ReqId::from_header("some-id");
        assert_eq!(id.as_str(), "some-id");
    }

    #[test]
    fn display_and_deref() {
        let id = ReqId::from_test("test-id");
        assert_eq!(format!("{}", id), "test-id");
        assert_eq!(id.len(), 7);
        assert!(id.starts_with("test"));
    }
}
