// @generated by a fixture codegen. DO NOT EDIT.

// Inline modules inside a generated file must NOT be linted: codegen owns the
// layout and the file is never hand-edited.
pub mod generated_inner {
    pub fn run() {}
}
