[package]
name = "trogon-channel"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
trogon-std = { workspace = true, features = ["uuid"] }

async-nats = { workspace = true, features = ["jetstream", "kv"] }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
